In [1]:
import numpy as np
import pandas as pd

Loading Data to preprocess.

In [2]:
df = pd.read_csv("../data/reddit.csv")
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [3]:
df.shape

(37249, 2)

In [4]:
df.sample()["clean_comment"].values

<StringArray>
['this post anti national and anti hindu ']
Length: 1, dtype: str

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37249 entries, 0 to 37248
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clean_comment  37149 non-null  str
 1   category       37249 non-null  int64
dtypes: int64(1), str(1)
memory usage: 582.1 KB

In [6]:
df.isnull().sum()

clean_comment    100
category           0
dtype: int64

In [7]:
df[df['clean_comment'].isna()]

      clean_comment  category
413             NaN         0
605             NaN         0
2422            NaN         0
2877            NaN         0
3307            NaN         0
...             ...       ...
35975           NaN         0
36036           NaN         0
37043           NaN         0
37111           NaN         0
37238           NaN         0

[100 rows x 2 columns]

In [8]:
df[df["clean_comment"].isna()]["category"].value_counts()

category
0    100
Name: count, dtype: int64

In [9]:
# Dropping all missing values for the clean_comments
df.dropna(inplace=True)
df.isnull().sum()

clean_comment    0
category         0
dtype: int64

In [10]:
# checking for duplicate comments and category
df.duplicated().sum()

np.int64(350)

In [11]:
df[df.duplicated()]

                                           clean_comment  category
375                                                              0
392                                                              0
617                                           aurum mom          0
651                                                              0
1222                                                             0
...                                                  ...       ...
36915                                           who won          0
37044                                                            0
37125                                              hari          0
37158                                           top kek          1
37234  this part series minute videos focusing each d...         1

[350 rows x 2 columns]

In [12]:
# Dropping all the duplicates 
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [18]:
# Checking for having a new line.
df[(df['clean_comment'].str.strip() == "")]

                clean_comment  category
181                                   0
4432                       \n         0
10592                                 0
16173                                 0
32149  \n                             0
34959                                 0

In [19]:
# Removing the new line from the data
df = df[~(df["clean_comment"].str.strip() == '')]

In [20]:
df[(df['clean_comment'].str.strip() == "")]

Empty DataFrame
Columns: [clean_comment, category]
Index: []

In [21]:
# Converting the "clean_comment" column to lowercase
df['clean_comment'] = df['clean_comment'].str.lower()

# Verify the transformation by displaying first 5 rows
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [22]:
# Checking for empty spaces at the beginning of the comments or at the end of the comment.
df[df['clean_comment'].apply(lambda x: x.startswith(" ") or x.endswith(" "))]

                                           clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37241            let the janta decide not ulema clerics          0
37242   hona hai same with vaccination education insu...         0
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[32266 rows x 2 columns]

In [23]:
# Remove trailing and leading white spaces from the "clean_comment" column
df["clean_comment"] = df["clean_comment"].str.strip()

# Verify the transformation by checking the data again
df['clean_comment'].apply(lambda x: x.startswith(" ") or x.endswith(" ")).sum()

np.int64(0)

In [25]:
# Checking comments containing URLs
url_pattern = r'^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,63}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$'
comments_with_urls = df[df['clean_comment'].str.contains(url_pattern, regex=True)]

comments_with_urls.head()

/tmp/ipykernel_35713/182289334.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  comments_with_urls = df[df['clean_comment'].str.contains(url_pattern, regex=True)]

Empty DataFrame
Columns: [clean_comment, category]
Index: []

In [26]:
# Checking for comments with new line characters that is `\n`
comments_with_newline = df[df['clean_comment'].str.contains('\n')]

In [27]:
comments_with_newline

                                           clean_comment  category
448    what missing jpg\nand why this brilliant edit ...         1
781    india has been ruined congress and populist sc...        -1
847    like aap for its stand corruption and making p...        -1
871    reduced trade\ndeficit stronger rupee aren the...         0
1354   amsa press conference australian maritime safe...         1
...                                                  ...       ...
35128  火箭o辛基 2016 sughosh bansal mission “make india”...        -1
35230  yikes the title should blind bhakts modi hater...         1
36187                 hahahahahhahahah \niska klpd hogya         0
36517                         ्ा् ी ाी े ो ेी ाी े।\nे ी         0
36919  y6sg1xuovbb0czfwjpug0h html\nfull credit anti ...         1

[204 rows x 2 columns]

In [28]:
# Remove new line characters from the "clean_comment" column by replacing the \n with space " "
df["clean_comment"] = df["clean_comment"].str.replace('\n', ' ', regex=True)

comments_with_newline_remaining = df[df['clean_comment'].str.contains('\n')]
comments_with_newline_remaining

Empty DataFrame
Columns: [clean_comment, category]
Index: []

### Exploratory Data Analysis (EDA)
- Definition: data analysis where we explore, summarize, and visualize data to understand its structure, detect patterns, identify anomalies, test assumptions, and check relationships between variables before applying any machine learning or statistical models.

In [29]:
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
# Distribution of Classes for the categories
# +1 is for positive comments
# -1 is for negative comments
# 0 is for neutral comments

sns.countplot(data = df, x = df['category'], y = df['clean_comment'])

TypeError: Cannot pass values for both `x` and `y`.